
package com.capgemini.transfer.ws.client;

/**
 * Please modify this class to meet your needs
 * This class is not complete
 */

import java.io.File;
import java.net.MalformedURLException;
import java.net.URL;

import javax.xml.namespace.QName;

/**
 * This class was generated by Apache CXF 3.1.12
 * 2017-07-11T11:46:17.642+08:00
 * Generated source version: 3.1.12
 * 
 */
public final class RequestResponseHRDataBinding_RequestResponseHRDataBinding1_Client {

    private static final QName SERVICE_NAME = new QName("http://ATS.online-onboarding.com/Client/HRDataServiceEx", "RequestResponseHRDataService");

    private RequestResponseHRDataBinding_RequestResponseHRDataBinding1_Client() {
    }

    public static void main(String args[]) throws java.lang.Exception {
        URL wsdlURL = RequestResponseHRDataService.WSDL_LOCATION;
        if (args.length > 0 && args[0] != null && !"".equals(args[0])) { 
            File wsdlFile = new File(args[0]);
            try {
                if (wsdlFile.exists()) {
                    wsdlURL = wsdlFile.toURI().toURL();
                } else {
                    wsdlURL = new URL(args[0]);
                }
            } catch (MalformedURLException e) {
                e.printStackTrace();
            }
        }
      
        RequestResponseHRDataService ss = new RequestResponseHRDataService(wsdlURL, SERVICE_NAME);
        RequestResponseHRDataBinding port = ss.getRequestResponseHRDataBinding1();  
        
        {
        System.out.println("Invoking cancelSession...");
        java.lang.String _cancelSession_ticket = "";
        port.cancelSession(_cancelSession_ticket);


        }
        {
        System.out.println("Invoking syncUsers...");
        java.lang.String _syncUsers_ticket = "";
        java.lang.String _syncUsers_data = "";
        java.lang.String _syncUsers__return = port.syncUsers(_syncUsers_ticket, _syncUsers_data);
        System.out.println("syncUsers.result=" + _syncUsers__return);


        }
        {
        System.out.println("Invoking postOffboardUserRecords...");
        java.lang.String _postOffboardUserRecords_ticket = "";
        java.lang.String _postOffboardUserRecords_data = "";
        java.lang.String _postOffboardUserRecords__return = port.postOffboardUserRecords(_postOffboardUserRecords_ticket, _postOffboardUserRecords_data);
        System.out.println("postOffboardUserRecords.result=" + _postOffboardUserRecords__return);


        }
        {
        System.out.println("Invoking getOffboardingActivityStatus...");
        java.lang.String _getOffboardingActivityStatus_ticket = "";
        java.lang.String _getOffboardingActivityStatus_hrDataID = "";
        java.lang.String _getOffboardingActivityStatus__return = port.getOffboardingActivityStatus(_getOffboardingActivityStatus_ticket, _getOffboardingActivityStatus_hrDataID);
        System.out.println("getOffboardingActivityStatus.result=" + _getOffboardingActivityStatus__return);


        }
        {
        System.out.println("Invoking postReferenceFiles...");
        java.lang.String _postReferenceFiles_ticket = "";
        java.lang.String _postReferenceFiles_data = "";
        java.lang.String _postReferenceFiles__return = port.postReferenceFiles(_postReferenceFiles_ticket, _postReferenceFiles_data);
        System.out.println("postReferenceFiles.result=" + _postReferenceFiles__return);


        }
        {
        System.out.println("Invoking getUserActivities...");
        java.lang.String _getUserActivities_ticket = "";
        java.lang.String _getUserActivities_userName = "";
        java.lang.String _getUserActivities__return = port.getUserActivities(_getUserActivities_ticket, _getUserActivities_userName);
        System.out.println("getUserActivities.result=" + _getUserActivities__return);


        }
        {
        System.out.println("Invoking getStatus...");
        java.lang.String _getStatus_ticket = "";
        java.lang.String _getStatus__return = port.getStatus(_getStatus_ticket);
        System.out.println("getStatus.result=" + _getStatus__return);


        }
        {
        System.out.println("Invoking addHRDataRecord...");
        java.lang.String _addHRDataRecord_ticket = "";
        java.lang.String _addHRDataRecord_newHireID = "";
        java.lang.String _addHRDataRecord_field = "";
        java.lang.String _addHRDataRecord_value = "";
        java.lang.String _addHRDataRecord__return = port.addHRDataRecord(_addHRDataRecord_ticket, _addHRDataRecord_newHireID, _addHRDataRecord_field, _addHRDataRecord_value);
        System.out.println("addHRDataRecord.result=" + _addHRDataRecord__return);


        }
        {
        System.out.println("Invoking syncUserWithEmail...");
        java.lang.String _syncUserWithEmail_ticket = "";
        java.lang.String _syncUserWithEmail_userID = "";
        java.lang.String _syncUserWithEmail_loginName = "";
        java.lang.String _syncUserWithEmail_firstName = "";
        java.lang.String _syncUserWithEmail_lastName = "";
        java.lang.String _syncUserWithEmail_userType = "";
        java.lang.String _syncUserWithEmail_status = "";
        int _syncUserWithEmail_externalId = 0;
        java.lang.String _syncUserWithEmail_email = "";
        java.lang.String _syncUserWithEmail__return = port.syncUserWithEmail(_syncUserWithEmail_ticket, _syncUserWithEmail_userID, _syncUserWithEmail_loginName, _syncUserWithEmail_firstName, _syncUserWithEmail_lastName, _syncUserWithEmail_userType, _syncUserWithEmail_status, _syncUserWithEmail_externalId, _syncUserWithEmail_email);
        System.out.println("syncUserWithEmail.result=" + _syncUserWithEmail__return);


        }
        {
        System.out.println("Invoking deleteReferenceFiles...");
        java.lang.String _deleteReferenceFiles_ticket = "";
        java.lang.String _deleteReferenceFiles_data = "";
        java.lang.String _deleteReferenceFiles__return = port.deleteReferenceFiles(_deleteReferenceFiles_ticket, _deleteReferenceFiles_data);
        System.out.println("deleteReferenceFiles.result=" + _deleteReferenceFiles__return);


        }
        {
        System.out.println("Invoking postNewhireRecord...");
        java.lang.String _postNewhireRecord_ticket = "";
        java.lang.String _postNewhireRecord_data = "";
        java.lang.String _postNewhireRecord__return = port.postNewhireRecord(_postNewhireRecord_ticket, _postNewhireRecord_data);
        System.out.println("postNewhireRecord.result=" + _postNewhireRecord__return);


        }
        {
        System.out.println("Invoking syncUserWithCorporateCodes...");
        java.lang.String _syncUserWithCorporateCodes_ticket = "";
        java.lang.String _syncUserWithCorporateCodes_userID = "";
        java.lang.String _syncUserWithCorporateCodes_loginName = "";
        java.lang.String _syncUserWithCorporateCodes_firstName = "";
        java.lang.String _syncUserWithCorporateCodes_lastName = "";
        java.lang.String _syncUserWithCorporateCodes_userType = "";
        java.lang.String _syncUserWithCorporateCodes_status = "";
        int _syncUserWithCorporateCodes_externalId = 0;
        java.lang.String _syncUserWithCorporateCodes_companyCode = "";
        java.lang.String _syncUserWithCorporateCodes_divisionCode = "";
        java.lang.String _syncUserWithCorporateCodes_locationCode = "";
        java.lang.String _syncUserWithCorporateCodes_departmentCode = "";
        java.lang.String _syncUserWithCorporateCodes__return = port.syncUserWithCorporateCodes(_syncUserWithCorporateCodes_ticket, _syncUserWithCorporateCodes_userID, _syncUserWithCorporateCodes_loginName, _syncUserWithCorporateCodes_firstName, _syncUserWithCorporateCodes_lastName, _syncUserWithCorporateCodes_userType, _syncUserWithCorporateCodes_status, _syncUserWithCorporateCodes_externalId, _syncUserWithCorporateCodes_companyCode, _syncUserWithCorporateCodes_divisionCode, _syncUserWithCorporateCodes_locationCode, _syncUserWithCorporateCodes_departmentCode);
        System.out.println("syncUserWithCorporateCodes.result=" + _syncUserWithCorporateCodes__return);


        }
        {
        System.out.println("Invoking syncUser...");
        java.lang.String _syncUser_ticket = "";
        java.lang.String _syncUser_userID = "";
        java.lang.String _syncUser_loginName = "";
        java.lang.String _syncUser_firstName = "";
        java.lang.String _syncUser_lastName = "";
        java.lang.String _syncUser_userType = "";
        java.lang.String _syncUser_status = "";
        int _syncUser_externalId = 0;
        java.lang.String _syncUser__return = port.syncUser(_syncUser_ticket, _syncUser_userID, _syncUser_loginName, _syncUser_firstName, _syncUser_lastName, _syncUser_userType, _syncUser_status, _syncUser_externalId);
        System.out.println("syncUser.result=" + _syncUser__return);


        }
        {
        System.out.println("Invoking postNewhireRecords...");
        java.lang.String _postNewhireRecords_ticket = "";
        java.lang.String _postNewhireRecords_data = "";
        java.lang.String _postNewhireRecords__return = port.postNewhireRecords(_postNewhireRecords_ticket, _postNewhireRecords_data);
        System.out.println("postNewhireRecords.result=" + _postNewhireRecords__return);


        }
        {
        System.out.println("Invoking offboardExistingUser...");
        java.lang.String _offboardExistingUser_ticket = "";
        java.lang.String _offboardExistingUser_loginName = "";
        java.lang.String _offboardExistingUser_userID = "";
        java.lang.String _offboardExistingUser_assignTo = "";
        java.lang.String _offboardExistingUser__return = port.offboardExistingUser(_offboardExistingUser_ticket, _offboardExistingUser_loginName, _offboardExistingUser_userID, _offboardExistingUser_assignTo);
        System.out.println("offboardExistingUser.result=" + _offboardExistingUser__return);


        }
        {
        System.out.println("Invoking deleteNewhireRecord...");
        java.lang.String _deleteNewhireRecord_ticket = "";
        java.lang.String _deleteNewhireRecord_newhireID = "";
        java.lang.String _deleteNewhireRecord__return = port.deleteNewhireRecord(_deleteNewhireRecord_ticket, _deleteNewhireRecord_newhireID);
        System.out.println("deleteNewhireRecord.result=" + _deleteNewhireRecord__return);


        }
        {
        System.out.println("Invoking postSebEvent...");
        java.lang.String _postSebEvent_ticket = "";
        java.lang.String _postSebEvent_eventType = "";
        java.lang.String _postSebEvent_eventData = "";
        java.lang.String _postSebEvent__return = port.postSebEvent(_postSebEvent_ticket, _postSebEvent_eventType, _postSebEvent_eventData);
        System.out.println("postSebEvent.result=" + _postSebEvent__return);


        }
        {
        System.out.println("Invoking deleteUser...");
        java.lang.String _deleteUser_ticket = "";
        java.lang.String _deleteUser_userLogin = "";
        java.lang.String _deleteUser_userExternalId = "";
        java.lang.String _deleteUser__return = port.deleteUser(_deleteUser_ticket, _deleteUser_userLogin, _deleteUser_userExternalId);
        System.out.println("deleteUser.result=" + _deleteUser__return);


        }
        {
        System.out.println("Invoking getNewhireRecordByExportId...");
        java.lang.String _getNewhireRecordByExportId_ticket = "";
        java.lang.String _getNewhireRecordByExportId_newhireID = "";
        java.lang.String _getNewhireRecordByExportId_exportID = "";
        java.lang.String _getNewhireRecordByExportId__return = port.getNewhireRecordByExportId(_getNewhireRecordByExportId_ticket, _getNewhireRecordByExportId_newhireID, _getNewhireRecordByExportId_exportID);
        System.out.println("getNewhireRecordByExportId.result=" + _getNewhireRecordByExportId__return);


        }
        {
        System.out.println("Invoking deleteOffboardRecord...");
        java.lang.String _deleteOffboardRecord_ticket = "";
        java.lang.String _deleteOffboardRecord_hrDataID = "";
        java.lang.String _deleteOffboardRecord__return = port.deleteOffboardRecord(_deleteOffboardRecord_ticket, _deleteOffboardRecord_hrDataID);
        System.out.println("deleteOffboardRecord.result=" + _deleteOffboardRecord__return);


        }
        {
        System.out.println("Invoking postBase64NewhireRecord...");
        java.lang.String _postBase64NewhireRecord_ticket = "";
        java.lang.String _postBase64NewhireRecord_data = "";
        java.lang.String _postBase64NewhireRecord__return = port.postBase64NewhireRecord(_postBase64NewhireRecord_ticket, _postBase64NewhireRecord_data);
        System.out.println("postBase64NewhireRecord.result=" + _postBase64NewhireRecord__return);


        }
        {
        System.out.println("Invoking getOffboardUserRecord...");
        java.lang.String _getOffboardUserRecord_ticket = "";
        java.lang.String _getOffboardUserRecord_hrDataID = "";
        java.lang.String _getOffboardUserRecord__return = port.getOffboardUserRecord(_getOffboardUserRecord_ticket, _getOffboardUserRecord_hrDataID);
        System.out.println("getOffboardUserRecord.result=" + _getOffboardUserRecord__return);


        }
        {
        System.out.println("Invoking getOffboardUserRecordWithExportId...");
        java.lang.String _getOffboardUserRecordWithExportId_ticket = "";
        java.lang.String _getOffboardUserRecordWithExportId_hrDataID = "";
        java.lang.String _getOffboardUserRecordWithExportId_exportID = "";
        java.lang.String _getOffboardUserRecordWithExportId__return = port.getOffboardUserRecordWithExportId(_getOffboardUserRecordWithExportId_ticket, _getOffboardUserRecordWithExportId_hrDataID, _getOffboardUserRecordWithExportId_exportID);
        System.out.println("getOffboardUserRecordWithExportId.result=" + _getOffboardUserRecordWithExportId__return);


        }
        {
        System.out.println("Invoking deleteHRDataRecord...");
        java.lang.String _deleteHRDataRecord_ticket = "";
        java.lang.String _deleteHRDataRecord_hrDataId = "";
        java.lang.String _deleteHRDataRecord_field = "";
        java.lang.String _deleteHRDataRecord__return = port.deleteHRDataRecord(_deleteHRDataRecord_ticket, _deleteHRDataRecord_hrDataId, _deleteHRDataRecord_field);
        System.out.println("deleteHRDataRecord.result=" + _deleteHRDataRecord__return);


        }
        {
        System.out.println("Invoking getActivityStatusEx...");
        java.lang.String _getActivityStatusEx_ticket = "";
        java.lang.String _getActivityStatusEx_newhireID = "";
        java.lang.String _getActivityStatusEx__return = port.getActivityStatusEx(_getActivityStatusEx_ticket, _getActivityStatusEx_newhireID);
        System.out.println("getActivityStatusEx.result=" + _getActivityStatusEx__return);


        }
        {
        System.out.println("Invoking beginSession...");
        java.lang.String _beginSession_name = "";
        java.lang.String _beginSession_password = "";
        java.lang.String _beginSession__return = port.beginSession(_beginSession_name, _beginSession_password);
        System.out.println("beginSession.result=" + _beginSession__return);


        }
        {
        System.out.println("Invoking getActivityStatus...");
        java.lang.String _getActivityStatus_ticket = "";
        java.lang.String _getActivityStatus_newhireID = "";
        java.lang.String _getActivityStatus__return = port.getActivityStatus(_getActivityStatus_ticket, _getActivityStatus_newhireID);
        System.out.println("getActivityStatus.result=" + _getActivityStatus__return);


        }
        {
        System.out.println("Invoking postOffboardUserRecord...");
        java.lang.String _postOffboardUserRecord_ticket = "";
        java.lang.String _postOffboardUserRecord_data = "";
        java.lang.String _postOffboardUserRecord__return = port.postOffboardUserRecord(_postOffboardUserRecord_ticket, _postOffboardUserRecord_data);
        System.out.println("postOffboardUserRecord.result=" + _postOffboardUserRecord__return);


        }
        {
        System.out.println("Invoking postNewhireRecordWithSupplementalData...");
        java.lang.String _postNewhireRecordWithSupplementalData_ticket = "";
        java.lang.String _postNewhireRecordWithSupplementalData_data = "";
        java.lang.String _postNewhireRecordWithSupplementalData_supplementalData = "";
        java.lang.String _postNewhireRecordWithSupplementalData__return = port.postNewhireRecordWithSupplementalData(_postNewhireRecordWithSupplementalData_ticket, _postNewhireRecordWithSupplementalData_data, _postNewhireRecordWithSupplementalData_supplementalData);
        System.out.println("postNewhireRecordWithSupplementalData.result=" + _postNewhireRecordWithSupplementalData__return);


        }
        {
        System.out.println("Invoking getNewhireRecord...");
        java.lang.String _getNewhireRecord_ticket = "";
        java.lang.String _getNewhireRecord_newhireID = "";
        java.lang.String _getNewhireRecord__return = port.getNewhireRecord(_getNewhireRecord_ticket, _getNewhireRecord_newhireID);
        System.out.println("getNewhireRecord.result=" + _getNewhireRecord__return);


        }

        System.exit(0);
    }

}
