
package com.capgemini.transfer.ws.client;

import javax.xml.ws.Endpoint;

/**
 * This class was generated by Apache CXF 3.1.12
 * 2017-07-11T11:46:17.735+08:00
 * Generated source version: 3.1.12
 * 
 */
 
public class RequestResponseHRDataBinding_RequestResponseHRDataBinding1_Server{

    protected RequestResponseHRDataBinding_RequestResponseHRDataBinding1_Server() throws java.lang.Exception {
        System.out.println("Starting Server");
        Object implementor = new RequestResponseHRDataBinding1Impl();
        String address = "https://onboarding15preview.sapsf.cn/ONBPREM/Services/HRDataServiceEx.asmx";
        Endpoint.publish(address, implementor);
    }
    
    public static void main(String args[]) throws java.lang.Exception { 
        new RequestResponseHRDataBinding_RequestResponseHRDataBinding1_Server();
        System.out.println("Server ready..."); 
        
        Thread.sleep(5 * 60 * 1000); 
        System.out.println("Server exiting");
        System.exit(0);
    }
}
