
/**
 * Please modify this class to meet your needs
 * This class is not complete
 */

package com.capgemini.transfer.ws.client;

import java.util.logging.Logger;

/**
 * This class was generated by Apache CXF 3.1.12
 * 2017-07-11T11:46:17.720+08:00
 * Generated source version: 3.1.12
 * 
 */

@javax.jws.WebService(
                      serviceName = "RequestResponseHRDataService",
                      portName = "RequestResponseHRDataBinding",
                      targetNamespace = "http://ATS.online-onboarding.com/Client/HRDataServiceEx",
                      wsdlLocation = "https://onboarding15preview.sapsf.cn/ONBPREM/Services/HRDataServiceEx.asmx?WSDL",
                      endpointInterface = "com.capgemini.transfer.ws.client.RequestResponseHRDataBinding")
                      
public class RequestResponseHRDataBindingImpl implements RequestResponseHRDataBinding {

    private static final Logger LOG = Logger.getLogger(RequestResponseHRDataBindingImpl.class.getName());

    /* (non-Javadoc)
     * @see com.capgemini.transfer.ws.client.RequestResponseHRDataBinding#cancelSession(java.lang.String ticket)*
     */
    public void cancelSession(java.lang.String ticket) { 
        LOG.info("Executing operation cancelSession");
        System.out.println(ticket);
        try {
        } catch (java.lang.Exception ex) {
            ex.printStackTrace();
            throw new RuntimeException(ex);
        }
    }

    /* (non-Javadoc)
     * @see com.capgemini.transfer.ws.client.RequestResponseHRDataBinding#syncUsers(java.lang.String ticket, java.lang.String data)*
     */
    public java.lang.String syncUsers(java.lang.String ticket, java.lang.String data) { 
        LOG.info("Executing operation syncUsers");
        System.out.println(ticket);
        System.out.println(data);
        try {
            java.lang.String _return = "";
            return _return;
        } catch (java.lang.Exception ex) {
            ex.printStackTrace();
            throw new RuntimeException(ex);
        }
    }

    /* (non-Javadoc)
     * @see com.capgemini.transfer.ws.client.RequestResponseHRDataBinding#postOffboardUserRecords(java.lang.String ticket, java.lang.String data)*
     */
    public java.lang.String postOffboardUserRecords(java.lang.String ticket, java.lang.String data) { 
        LOG.info("Executing operation postOffboardUserRecords");
        System.out.println(ticket);
        System.out.println(data);
        try {
            java.lang.String _return = "";
            return _return;
        } catch (java.lang.Exception ex) {
            ex.printStackTrace();
            throw new RuntimeException(ex);
        }
    }

    /* (non-Javadoc)
     * @see com.capgemini.transfer.ws.client.RequestResponseHRDataBinding#getOffboardingActivityStatus(java.lang.String ticket, java.lang.String hrDataID)*
     */
    public java.lang.String getOffboardingActivityStatus(java.lang.String ticket, java.lang.String hrDataID) { 
        LOG.info("Executing operation getOffboardingActivityStatus");
        System.out.println(ticket);
        System.out.println(hrDataID);
        try {
            java.lang.String _return = "";
            return _return;
        } catch (java.lang.Exception ex) {
            ex.printStackTrace();
            throw new RuntimeException(ex);
        }
    }

    /* (non-Javadoc)
     * @see com.capgemini.transfer.ws.client.RequestResponseHRDataBinding#postReferenceFiles(java.lang.String ticket, java.lang.String data)*
     */
    public java.lang.String postReferenceFiles(java.lang.String ticket, java.lang.String data) { 
        LOG.info("Executing operation postReferenceFiles");
        System.out.println(ticket);
        System.out.println(data);
        try {
            java.lang.String _return = "";
            return _return;
        } catch (java.lang.Exception ex) {
            ex.printStackTrace();
            throw new RuntimeException(ex);
        }
    }

    /* (non-Javadoc)
     * @see com.capgemini.transfer.ws.client.RequestResponseHRDataBinding#getUserActivities(java.lang.String ticket, java.lang.String userName)*
     */
    public java.lang.String getUserActivities(java.lang.String ticket, java.lang.String userName) { 
        LOG.info("Executing operation getUserActivities");
        System.out.println(ticket);
        System.out.println(userName);
        try {
            java.lang.String _return = "";
            return _return;
        } catch (java.lang.Exception ex) {
            ex.printStackTrace();
            throw new RuntimeException(ex);
        }
    }

    /* (non-Javadoc)
     * @see com.capgemini.transfer.ws.client.RequestResponseHRDataBinding#getStatus(java.lang.String ticket)*
     */
    public java.lang.String getStatus(java.lang.String ticket) { 
        LOG.info("Executing operation getStatus");
        System.out.println(ticket);
        try {
            java.lang.String _return = "";
            return _return;
        } catch (java.lang.Exception ex) {
            ex.printStackTrace();
            throw new RuntimeException(ex);
        }
    }

    /* (non-Javadoc)
     * @see com.capgemini.transfer.ws.client.RequestResponseHRDataBinding#addHRDataRecord(java.lang.String ticket, java.lang.String newHireID, java.lang.String field, java.lang.String value)*
     */
    public java.lang.String addHRDataRecord(java.lang.String ticket, java.lang.String newHireID, java.lang.String field, java.lang.String value) { 
        LOG.info("Executing operation addHRDataRecord");
        System.out.println(ticket);
        System.out.println(newHireID);
        System.out.println(field);
        System.out.println(value);
        try {
            java.lang.String _return = "";
            return _return;
        } catch (java.lang.Exception ex) {
            ex.printStackTrace();
            throw new RuntimeException(ex);
        }
    }

    /* (non-Javadoc)
     * @see com.capgemini.transfer.ws.client.RequestResponseHRDataBinding#syncUserWithEmail(java.lang.String ticket, java.lang.String userID, java.lang.String loginName, java.lang.String firstName, java.lang.String lastName, java.lang.String userType, java.lang.String status, int externalId, java.lang.String email)*
     */
    public java.lang.String syncUserWithEmail(java.lang.String ticket, java.lang.String userID, java.lang.String loginName, java.lang.String firstName, java.lang.String lastName, java.lang.String userType, java.lang.String status, int externalId, java.lang.String email) { 
        LOG.info("Executing operation syncUserWithEmail");
        System.out.println(ticket);
        System.out.println(userID);
        System.out.println(loginName);
        System.out.println(firstName);
        System.out.println(lastName);
        System.out.println(userType);
        System.out.println(status);
        System.out.println(externalId);
        System.out.println(email);
        try {
            java.lang.String _return = "";
            return _return;
        } catch (java.lang.Exception ex) {
            ex.printStackTrace();
            throw new RuntimeException(ex);
        }
    }

    /* (non-Javadoc)
     * @see com.capgemini.transfer.ws.client.RequestResponseHRDataBinding#deleteReferenceFiles(java.lang.String ticket, java.lang.String data)*
     */
    public java.lang.String deleteReferenceFiles(java.lang.String ticket, java.lang.String data) { 
        LOG.info("Executing operation deleteReferenceFiles");
        System.out.println(ticket);
        System.out.println(data);
        try {
            java.lang.String _return = "";
            return _return;
        } catch (java.lang.Exception ex) {
            ex.printStackTrace();
            throw new RuntimeException(ex);
        }
    }

    /* (non-Javadoc)
     * @see com.capgemini.transfer.ws.client.RequestResponseHRDataBinding#postNewhireRecord(java.lang.String ticket, java.lang.String data)*
     */
    public java.lang.String postNewhireRecord(java.lang.String ticket, java.lang.String data) { 
        LOG.info("Executing operation postNewhireRecord");
        System.out.println(ticket);
        System.out.println(data);
        try {
            java.lang.String _return = "";
            return _return;
        } catch (java.lang.Exception ex) {
            ex.printStackTrace();
            throw new RuntimeException(ex);
        }
    }

    /* (non-Javadoc)
     * @see com.capgemini.transfer.ws.client.RequestResponseHRDataBinding#syncUserWithCorporateCodes(java.lang.String ticket, java.lang.String userID, java.lang.String loginName, java.lang.String firstName, java.lang.String lastName, java.lang.String userType, java.lang.String status, int externalId, java.lang.String companyCode, java.lang.String divisionCode, java.lang.String locationCode, java.lang.String departmentCode)*
     */
    public java.lang.String syncUserWithCorporateCodes(java.lang.String ticket, java.lang.String userID, java.lang.String loginName, java.lang.String firstName, java.lang.String lastName, java.lang.String userType, java.lang.String status, int externalId, java.lang.String companyCode, java.lang.String divisionCode, java.lang.String locationCode, java.lang.String departmentCode) { 
        LOG.info("Executing operation syncUserWithCorporateCodes");
        System.out.println(ticket);
        System.out.println(userID);
        System.out.println(loginName);
        System.out.println(firstName);
        System.out.println(lastName);
        System.out.println(userType);
        System.out.println(status);
        System.out.println(externalId);
        System.out.println(companyCode);
        System.out.println(divisionCode);
        System.out.println(locationCode);
        System.out.println(departmentCode);
        try {
            java.lang.String _return = "";
            return _return;
        } catch (java.lang.Exception ex) {
            ex.printStackTrace();
            throw new RuntimeException(ex);
        }
    }

    /* (non-Javadoc)
     * @see com.capgemini.transfer.ws.client.RequestResponseHRDataBinding#syncUser(java.lang.String ticket, java.lang.String userID, java.lang.String loginName, java.lang.String firstName, java.lang.String lastName, java.lang.String userType, java.lang.String status, int externalId)*
     */
    public java.lang.String syncUser(java.lang.String ticket, java.lang.String userID, java.lang.String loginName, java.lang.String firstName, java.lang.String lastName, java.lang.String userType, java.lang.String status, int externalId) { 
        LOG.info("Executing operation syncUser");
        System.out.println(ticket);
        System.out.println(userID);
        System.out.println(loginName);
        System.out.println(firstName);
        System.out.println(lastName);
        System.out.println(userType);
        System.out.println(status);
        System.out.println(externalId);
        try {
            java.lang.String _return = "";
            return _return;
        } catch (java.lang.Exception ex) {
            ex.printStackTrace();
            throw new RuntimeException(ex);
        }
    }

    /* (non-Javadoc)
     * @see com.capgemini.transfer.ws.client.RequestResponseHRDataBinding#postNewhireRecords(java.lang.String ticket, java.lang.String data)*
     */
    public java.lang.String postNewhireRecords(java.lang.String ticket, java.lang.String data) { 
        LOG.info("Executing operation postNewhireRecords");
        System.out.println(ticket);
        System.out.println(data);
        try {
            java.lang.String _return = "";
            return _return;
        } catch (java.lang.Exception ex) {
            ex.printStackTrace();
            throw new RuntimeException(ex);
        }
    }

    /* (non-Javadoc)
     * @see com.capgemini.transfer.ws.client.RequestResponseHRDataBinding#offboardExistingUser(java.lang.String ticket, java.lang.String loginName, java.lang.String userID, java.lang.String assignTo)*
     */
    public java.lang.String offboardExistingUser(java.lang.String ticket, java.lang.String loginName, java.lang.String userID, java.lang.String assignTo) { 
        LOG.info("Executing operation offboardExistingUser");
        System.out.println(ticket);
        System.out.println(loginName);
        System.out.println(userID);
        System.out.println(assignTo);
        try {
            java.lang.String _return = "";
            return _return;
        } catch (java.lang.Exception ex) {
            ex.printStackTrace();
            throw new RuntimeException(ex);
        }
    }

    /* (non-Javadoc)
     * @see com.capgemini.transfer.ws.client.RequestResponseHRDataBinding#deleteNewhireRecord(java.lang.String ticket, java.lang.String newhireID)*
     */
    public java.lang.String deleteNewhireRecord(java.lang.String ticket, java.lang.String newhireID) { 
        LOG.info("Executing operation deleteNewhireRecord");
        System.out.println(ticket);
        System.out.println(newhireID);
        try {
            java.lang.String _return = "";
            return _return;
        } catch (java.lang.Exception ex) {
            ex.printStackTrace();
            throw new RuntimeException(ex);
        }
    }

    /* (non-Javadoc)
     * @see com.capgemini.transfer.ws.client.RequestResponseHRDataBinding#postSebEvent(java.lang.String ticket, java.lang.String eventType, java.lang.String eventData)*
     */
    public java.lang.String postSebEvent(java.lang.String ticket, java.lang.String eventType, java.lang.String eventData) { 
        LOG.info("Executing operation postSebEvent");
        System.out.println(ticket);
        System.out.println(eventType);
        System.out.println(eventData);
        try {
            java.lang.String _return = "";
            return _return;
        } catch (java.lang.Exception ex) {
            ex.printStackTrace();
            throw new RuntimeException(ex);
        }
    }

    /* (non-Javadoc)
     * @see com.capgemini.transfer.ws.client.RequestResponseHRDataBinding#deleteUser(java.lang.String ticket, java.lang.String userLogin, java.lang.String userExternalId)*
     */
    public java.lang.String deleteUser(java.lang.String ticket, java.lang.String userLogin, java.lang.String userExternalId) { 
        LOG.info("Executing operation deleteUser");
        System.out.println(ticket);
        System.out.println(userLogin);
        System.out.println(userExternalId);
        try {
            java.lang.String _return = "";
            return _return;
        } catch (java.lang.Exception ex) {
            ex.printStackTrace();
            throw new RuntimeException(ex);
        }
    }

    /* (non-Javadoc)
     * @see com.capgemini.transfer.ws.client.RequestResponseHRDataBinding#getNewhireRecordByExportId(java.lang.String ticket, java.lang.String newhireID, java.lang.String exportID)*
     */
    public java.lang.String getNewhireRecordByExportId(java.lang.String ticket, java.lang.String newhireID, java.lang.String exportID) { 
        LOG.info("Executing operation getNewhireRecordByExportId");
        System.out.println(ticket);
        System.out.println(newhireID);
        System.out.println(exportID);
        try {
            java.lang.String _return = "";
            return _return;
        } catch (java.lang.Exception ex) {
            ex.printStackTrace();
            throw new RuntimeException(ex);
        }
    }

    /* (non-Javadoc)
     * @see com.capgemini.transfer.ws.client.RequestResponseHRDataBinding#deleteOffboardRecord(java.lang.String ticket, java.lang.String hrDataID)*
     */
    public java.lang.String deleteOffboardRecord(java.lang.String ticket, java.lang.String hrDataID) { 
        LOG.info("Executing operation deleteOffboardRecord");
        System.out.println(ticket);
        System.out.println(hrDataID);
        try {
            java.lang.String _return = "";
            return _return;
        } catch (java.lang.Exception ex) {
            ex.printStackTrace();
            throw new RuntimeException(ex);
        }
    }

    /* (non-Javadoc)
     * @see com.capgemini.transfer.ws.client.RequestResponseHRDataBinding#postBase64NewhireRecord(java.lang.String ticket, java.lang.String data)*
     */
    public java.lang.String postBase64NewhireRecord(java.lang.String ticket, java.lang.String data) { 
        LOG.info("Executing operation postBase64NewhireRecord");
        System.out.println(ticket);
        System.out.println(data);
        try {
            java.lang.String _return = "";
            return _return;
        } catch (java.lang.Exception ex) {
            ex.printStackTrace();
            throw new RuntimeException(ex);
        }
    }

    /* (non-Javadoc)
     * @see com.capgemini.transfer.ws.client.RequestResponseHRDataBinding#getOffboardUserRecord(java.lang.String ticket, java.lang.String hrDataID)*
     */
    public java.lang.String getOffboardUserRecord(java.lang.String ticket, java.lang.String hrDataID) { 
        LOG.info("Executing operation getOffboardUserRecord");
        System.out.println(ticket);
        System.out.println(hrDataID);
        try {
            java.lang.String _return = "";
            return _return;
        } catch (java.lang.Exception ex) {
            ex.printStackTrace();
            throw new RuntimeException(ex);
        }
    }

    /* (non-Javadoc)
     * @see com.capgemini.transfer.ws.client.RequestResponseHRDataBinding#getOffboardUserRecordWithExportId(java.lang.String ticket, java.lang.String hrDataID, java.lang.String exportID)*
     */
    public java.lang.String getOffboardUserRecordWithExportId(java.lang.String ticket, java.lang.String hrDataID, java.lang.String exportID) { 
        LOG.info("Executing operation getOffboardUserRecordWithExportId");
        System.out.println(ticket);
        System.out.println(hrDataID);
        System.out.println(exportID);
        try {
            java.lang.String _return = "";
            return _return;
        } catch (java.lang.Exception ex) {
            ex.printStackTrace();
            throw new RuntimeException(ex);
        }
    }

    /* (non-Javadoc)
     * @see com.capgemini.transfer.ws.client.RequestResponseHRDataBinding#deleteHRDataRecord(java.lang.String ticket, java.lang.String hrDataId, java.lang.String field)*
     */
    public java.lang.String deleteHRDataRecord(java.lang.String ticket, java.lang.String hrDataId, java.lang.String field) { 
        LOG.info("Executing operation deleteHRDataRecord");
        System.out.println(ticket);
        System.out.println(hrDataId);
        System.out.println(field);
        try {
            java.lang.String _return = "";
            return _return;
        } catch (java.lang.Exception ex) {
            ex.printStackTrace();
            throw new RuntimeException(ex);
        }
    }

    /* (non-Javadoc)
     * @see com.capgemini.transfer.ws.client.RequestResponseHRDataBinding#getActivityStatusEx(java.lang.String ticket, java.lang.String newhireID)*
     */
    public java.lang.String getActivityStatusEx(java.lang.String ticket, java.lang.String newhireID) { 
        LOG.info("Executing operation getActivityStatusEx");
        System.out.println(ticket);
        System.out.println(newhireID);
        try {
            java.lang.String _return = "";
            return _return;
        } catch (java.lang.Exception ex) {
            ex.printStackTrace();
            throw new RuntimeException(ex);
        }
    }

    /* (non-Javadoc)
     * @see com.capgemini.transfer.ws.client.RequestResponseHRDataBinding#beginSession(java.lang.String name, java.lang.String password)*
     */
    public java.lang.String beginSession(java.lang.String name, java.lang.String password) { 
        LOG.info("Executing operation beginSession");
        System.out.println(name);
        System.out.println(password);
        try {
            java.lang.String _return = "";
            return _return;
        } catch (java.lang.Exception ex) {
            ex.printStackTrace();
            throw new RuntimeException(ex);
        }
    }

    /* (non-Javadoc)
     * @see com.capgemini.transfer.ws.client.RequestResponseHRDataBinding#getActivityStatus(java.lang.String ticket, java.lang.String newhireID)*
     */
    public java.lang.String getActivityStatus(java.lang.String ticket, java.lang.String newhireID) { 
        LOG.info("Executing operation getActivityStatus");
        System.out.println(ticket);
        System.out.println(newhireID);
        try {
            java.lang.String _return = "";
            return _return;
        } catch (java.lang.Exception ex) {
            ex.printStackTrace();
            throw new RuntimeException(ex);
        }
    }

    /* (non-Javadoc)
     * @see com.capgemini.transfer.ws.client.RequestResponseHRDataBinding#postOffboardUserRecord(java.lang.String ticket, java.lang.String data)*
     */
    public java.lang.String postOffboardUserRecord(java.lang.String ticket, java.lang.String data) { 
        LOG.info("Executing operation postOffboardUserRecord");
        System.out.println(ticket);
        System.out.println(data);
        try {
            java.lang.String _return = "";
            return _return;
        } catch (java.lang.Exception ex) {
            ex.printStackTrace();
            throw new RuntimeException(ex);
        }
    }

    /* (non-Javadoc)
     * @see com.capgemini.transfer.ws.client.RequestResponseHRDataBinding#postNewhireRecordWithSupplementalData(java.lang.String ticket, java.lang.String data, java.lang.String supplementalData)*
     */
    public java.lang.String postNewhireRecordWithSupplementalData(java.lang.String ticket, java.lang.String data, java.lang.String supplementalData) { 
        LOG.info("Executing operation postNewhireRecordWithSupplementalData");
        System.out.println(ticket);
        System.out.println(data);
        System.out.println(supplementalData);
        try {
            java.lang.String _return = "";
            return _return;
        } catch (java.lang.Exception ex) {
            ex.printStackTrace();
            throw new RuntimeException(ex);
        }
    }

    /* (non-Javadoc)
     * @see com.capgemini.transfer.ws.client.RequestResponseHRDataBinding#getNewhireRecord(java.lang.String ticket, java.lang.String newhireID)*
     */
    public java.lang.String getNewhireRecord(java.lang.String ticket, java.lang.String newhireID) { 
        LOG.info("Executing operation getNewhireRecord");
        System.out.println(ticket);
        System.out.println(newhireID);
        try {
            java.lang.String _return = "";
            return _return;
        } catch (java.lang.Exception ex) {
            ex.printStackTrace();
            throw new RuntimeException(ex);
        }
    }

}
